### ISSUE TITLE
OKIT web GUI non-responsive

### ISSUE THREAD

**Issue by rkasibhatla** [oracle/oci-designer-toolkit#736]
Hi

I tried installing the okit web using native installation on both ol8 and ol9 and also using docker image based install. I am following the exact step-by-step procedure. though the web interface is accessible, none of the GUI areas are working. I am not able to query an existing tenancy, nor i could able to add a new tenancy info using the green "wheel" button. its just non-responsive. the okit.log and okit-debug.log are not showing and error at all.

is there any specific issue with any dependencies ?

thanks

**Comment by xjuarez** [comment]
I have the same problem, do you have a solution?

**Comment by rkasibhatla** [comment]
Nop...no clue at all.
I tried all these combinations...

OEL9: native as well as Docker
OEL8: native as well as  Docker
Ubuntu 24
Ubuntu 20
WSL2 with Windows 11

nothing seems to work. earlier versions worked seamlessly with the fast docker based run. but this latest version is not at all working.

tried cloning until 0.60.0, but the same trouble persists.

the documentation is not precise regading the version compatibilities, package dependencies etc...so its like groping in the dark.

hope somebody looks into the issue to give a solution ASAP.

**Comment by obingul** [comment]
Same here

**Comment by xjuarez** [comment]
I was able to continue but it was with ocd-0.2.6-Setup.exe, this installs the app and does the same for the .oci .ssh issue, you must place it in C:\Users\User\

**Comment by rkasibhatla** [comment]
Hi

Yes the local installable OCD works fine...no issue with that. However it still has a lot of scope for improvement in its coming releases. Because,

1) AS per the documentation OCD has only a partial functionality comparted to the OKIT Web
2) The way in which the OCD creates the drawings up on querying an existing OCI environment is very awkward and is not presentation friendly. and moving around all the components even for a simple deployment is very clumsy to make it human understandable.

Regards

**Comment by BaumSchorle** [comment]
The Problem is a syntax error in the added jquery3.6.0.js library. You can simply replace the library with version 3.6.1 and then everything works again.

**Comment by rkasibhatla** [comment]
Hi

I have set up two clean VMs from scratch one with OL8.10 and the other with OL9.5
followed the exact steps as per the documentation, and after that replaced the jquery.js as per your advice.

in none of the environments it worked. The GUI is still non-responsive.

If you can share the exact configuration versions from the OS, Python and its modules, etc. where the web interface worked for your correctly, I would like to recreate an exact environment to see if it works for me too.

Thanks a lot.

Regards

**Comment by BaumSchorle** [comment]
Hi,

I have forked the repository and implemented a fix in Branch "736-fixes".

Then I simply built a new Docker image and it worked. It is important to update the Dockerfile, since it will pull the code from the repository to point to the fork and use "--build-arg BRANCH=736-fixes" while building the Docker image to pull the correct branch.

You should be able to download my fork and when using the correct branch and above args to build a working docker image.

This simply worked on my environment. 

The bug was introduced with this commit: https://github.com/oracle/oci-designer-toolkit/commit/b872c749a5ed4ebdd47db12fa883fb6384fe54be
The developer changed the jquery code and did introduce the syntax errors. You can check the Developer Tools of your browser and you will find the error in the console.

**Comment by rkasibhatla** [comment]
Hi

Good Day.

Thank you very much for your explanation and the effort you had put into this issue. 
In the first place just to confirm that yesterday I have tried the native linux installation method not the docker method.

I have two questions though:

1) It seems that the "dockering" feature is being de-emphasized as of the latest version. In this case, the modification you suggested regarding the jquery won't work in a native linux installation method ?

2) As you have forked this with a bug etc., can we expect this issued getting resolved in the next stable version?

Thank you very much.

Regards

Ravi

**Comment by sbarberuk** [comment]
> The Problem is a syntax error in the added jquery3.6.0.js library. You can simply replace the library with version 3.6.1 and then everything works again.

I did something similar, only with the latest version of jquery

```
cd okit/okitweb/static/js
mv jquery-3.6.0.js jquery-3.6.0.js.old
wget https://code.jquery.com/jquery-3.7.1.js
mv jquery-3.7.1.js jquery-3.6.0.js
```

**Comment by silencedapple** [comment]
I tried the installation based on the above recommendation and got everything to work except query for compartment, somehow it is doing query for dallas region for which I am getting a timeout (not subscribed to dallas) 

Jan 25 05:47:27 okit-4-ocpu gunicorn[142321]: [2025-01-25 05:47:27 +0000] [142321] [INFO] Starting gunicorn 23.0.0
Jan 25 05:47:27 okit-4-ocpu gunicorn[142321]: [2025-01-25 05:47:27 +0000] [142321] [INFO] Listening at: http://0.0.0.0:80 (142321)
Jan 25 05:47:27 okit-4-ocpu gunicorn[142321]: [2025-01-25 05:47:27 +0000] [142321] [INFO] Using worker: sync
Jan 25 05:47:27 okit-4-ocpu gunicorn[142323]: [2025-01-25 05:47:27 +0000] [142323] [INFO] Booting worker with pid: 142323
Jan 25 05:47:28 okit-4-ocpu gunicorn[142324]: [2025-01-25 05:47:28 +0000] [142324] [INFO] Booting worker with pid: 142324
Jan 25 05:47:28 okit-4-ocpu gunicorn[142325]: [2025-01-25 05:47:28 +0000] [142325] [INFO] Booting worker with pid: 142325
Jan 25 05:47:28 okit-4-ocpu gunicorn[142323]: INFO: Default Auth client Circuit breaker strategy enabled
Jan 25 05:47:28 okit-4-ocpu gunicorn[142330]: [2025-01-25 05:47:28 +0000] [142330] [INFO] Booting worker with pid: 142330
Jan 25 05:47:28 okit-4-ocpu gunicorn[142324]: INFO: Default Auth client Circuit breaker strategy enabled
Jan 25 05:47:28 okit-4-ocpu gunicorn[142325]: INFO: Default Auth client Circuit breaker strategy enabled
Jan 25 05:47:28 okit-4-ocpu gunicorn[142330]: INFO: Default Auth client Circuit breaker strategy enabled
Jan 25 05:47:42 okit-4-ocpu gunicorn[142325]: INFO: >>>>> Reading Cache
Jan 25 05:47:44 okit-4-ocpu gunicorn[142324]: INFO: Read Config: <configparser.ConfigParser object at 0x7f40f23ddfd0>
Jan 25 05:47:44 okit-4-ocpu gunicorn[142324]: INFO: Config Section: DEFAULT - has tenancy True
Jan 25 05:47:44 okit-4-ocpu gunicorn[142324]: INFO: Config Sections ['DEFAULT']
Jan 25 05:47:44 okit-4-ocpu gunicorn[142324]: INFO: Config Sections {'sections': ['DEFAULT']}
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Read Config: <configparser.ConfigParser object at 0x7f40f23bc040>
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Config Section: DEFAULT - has tenancy True
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Config Sections ['DEFAULT']
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Config Regions Sections {'sections': ['DEFAULT'], 'regions': {'DEFAULT': 'ap-sydney-1'}}
Jan 25 05:47:44 okit-4-ocpu gunicorn[142324]: INFO: {'valid': True, 'errors': [], 'sections': {'DEFAULT': {'valid': True}}}
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Config Sections [{'section': 'DEFAULT', 'valid': True, 'reason': ''}]
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Config Sections {'sections': [{'section': 'DEFAULT', 'valid': True, 'reason': ''}]}
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: []
Jan 25 05:47:44 okit-4-ocpu gunicorn[142323]: INFO: Config Settings {'gitsections': []}
Jan 25 05:47:44 okit-4-ocpu gunicorn[142325]: INFO: []
Jan 25 05:47:52 okit-4-ocpu gunicorn[142330]: INFO: Querying Compartments{'log_requests': False, 'additional_user_agent': 'OKIT v0.66.1', 'pass_phrase': None, 'user': 'ocid1.user.oc1..aaaaaaaagq3dembehesb7lgc>
Jan 25 05:47:52 okit-4-ocpu gunicorn[142330]: INFO: submitted 10 list resources requests
Jan 25 05:49:52 okit-4-ocpu gunicorn[142330]: ERROR: ('get_resources()', ('us-dallas-1', 'AvailabilityDomain', 'ocid1.tenancy.oc1..aaaaaaaaiotpdtr5vjdvmgmmhd4ymcpkxm27gieclpqbdarwh4rz7z36xhgq', None), Timeout>
Jan 25 05:49:52 okit-4-ocpu gunicorn[142330]: INFO: processed 9 list resources responses

**Comment by markkempers** [comment]
> > The Problem is a syntax error in the added jquery3.6.0.js library. You can simply replace the library with version 3.6.1 and then everything works again.
> 
> I did something similar, only with the latest version of jquery
> 
> ```
> cd okit/okitweb/static/js
> mv jquery-3.6.0.js jquery-3.6.0.js.old
> wget https://code.jquery.com/jquery-3.7.1.js
> mv jquery-3.7.1.js jquery-3.6.0.js
> ```


This did not fix it for met either. Any plans to implement a permanent fix?
